replicaCount: 1

image:
  repository: akashte/personalvaultapi
  pullPolicy: Always
  tag: "latest"

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080
  nodePort: 30081

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}