apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "personalvault-api.fullname" . }}
  labels:
    {{- include "personalvault-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "personalvault-api.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "personalvault-api.name" . }}
    spec:
      containers:
        - name: personalvault-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080