name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore PersonalVault.sln

      - name: Build
        run: dotnet build PersonalVault.sln --configuration Release --no-restore

      - name: Build Docker image
        run: docker build -t personalvaultapi:latest -f Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and push image to Docker Hub
        run: |
          docker tag personalvaultapi ${{ secrets.DOCKER_USERNAME }}/personalvaultapi:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/personalvaultapi:latest